# Change these first
owner: shijir0927
repo: bk-status-page

sites:
  - name: BackerKit Crowdfunding
    url: https://www.backerkit.com/
  - name: BackerKit Blog
    url: https://www.backerkit.com/blog/
  - name: BackerKit BackerTracker
    url: https://www.backerkit.com/backertracker
  - name: BackerKit Help Center
    url: https://help.backerkit.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /bk-status-page
  logoUrl: https://raw.githubusercontent.com/shijir0927/bk-status-page/refs/heads/master/assets/bk-icon.png
  name: BackerKit
  introTitle: "**BackerKit** is the best crowdfunding and pledge manager platform"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/BackerKit/status-page).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/BackerKit/status-page
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
